---
name: github
provider: github.com
repository: docker-markdownlint
url: https://github.com/cardboardci/docker-markdownlint
clone:
  ssh: git@github.com:cardboardci/docker-markdownlint.git
  https: https://github.com/cardboardci/docker-markdownlint.git